### ISSUE TITLE
Clojure/ClojureScript support?

### ISSUE THREAD

**Issue by chase-lambert** [yaegassy/coc-tailwindcss3#11]
I realize this is probably going to be too big of an ask and wishful thinking but I was wondering if you knew how I could get the tailwind autocompletion working with Clojure and Clojurescript, particularly when using the reagent and/or hiccup libraries which allows for a great Clojure-ish way of writing html that looks like: 
```
(defn simple-component []
  [:div
   [:p "Classes can be added in a traditional manner using a clojure hashmap with a :class keyword like:"]
   [:p {:class "text-2xl font-extrabold mt-6"}]
   [:p "or can be added using a shortcut syntax of just a '.' after an html element like:"]
   [:p.text-2xl.font-extrabold.mt-6]])
```
If it's even possible I imagine the traditional way would be the only way to make it happen. I haven't wrapped my head around how you actually identify when to trigger the autocompletion but I imagine you recognize an eligible file and then look for the 'class' keyword as a trigger? 

In this case, maybe if someone puts something like `"tailwindCSS.includeLanguages": { "clojure": "html"}` (which would be for files that end in `.clj, .cljs, or .cljc`) in the coc config file you can search for the `:class` keyword, or maybe anything that starts with a `:<anything>.` as anything after that `.` would be a css class, and then trigger the tailwind autocompletion.

**Comment by yaegassy** [comment]
Hi,

I've never used ClojureScript, so I can't verify it, but I found this ClojureScript thing in an issue report on uptream.

- <https://github.com/tailwindlabs/tailwindcss-intellisense/issues/400#issuecomment-916973975>

The `tailwindCSS.experimental.classRegex` setting is also available in `coc-tailwindcss3`, so try it.

**Comment by chase-lambert** [comment]
It's working! I think I also have to have  
```
  "tailwindCSS.includeLanguages": {                                                              
    "clojure": "html"             
  }   
```
As I don't think `"clojurescript": "html"` was recognizable. 

Now off to figure out the proper regex for the `[:h1.text-3xl.font-extrabold]` shorthand way to write CSS classes.
Thanks so much for the help and quick response.

**Comment by chase-lambert** [comment]
Hey, thought I would share this for those who end up here in the future, some nice folks on the Clojure slack helped me find this full solution that gives you autocompletion using both styles of hiccup (eg. `[:h1 {:class "text-3xl font-extrabold mt-6"} "Hello, World!]` and `[:div.text-3xl.font-extrabold.mt-6 "Hello, World!]`): 

```
 "tailwindCSS.experimental.classRegex": [                                                       
    ":class\\s+\"([^\"]*)\"",                                                                    
    ":[\\w-.#>]+\\.([\\w-]*)"                                                                    
  ],                                                                                             
  "tailwindCSS.includeLanguages": {                                                              
    "clojure": "html"                                                                            
  }
