### ISSUE TITLE
Failed installing

### ISSUE THREAD

**Issue by ghost** [yaegassy/coc-tailwindcss3#14]
![Screenshot_20220920-010814_Termux](https://user-images.githubusercontent.com/112737993/191085274-7995aab3-20e6-491f-bb33-40ef2c5fd593.jpg)

Maybe you can help..?

**Comment by yaegassy** [comment]
I cannot reproduce this problem in my environment. if coc.nvim is out of date, please update coc.nvim itself and try again.

If the problem persists, please report the issue to coc.nvim, as it may be a bug in coc.nvim.
