### ISSUE TITLE
Question: enable for typescriptreact

### ISSUE THREAD

**Issue by alextes** [yaegassy/coc-tailwindcss3#15]
Hi, when I work on typescriptreact files this extension doesn't seem to enable itself. Is that intentional? I tried to check the options and set `tailwindCSS.includedLanguages` but that didn't seem to do much.

How does one enable this extension for `typescriptreact` files?

**Comment by yaegassy** [comment]
The filetypes listed in this file are enabled by default. <https://github.com/yaegassy/coc-tailwindcss3/blob/master/src/util/languages.ts>

`typescriptreact` is, of course, enabled by default. It works in my environment.

If coc.nvim is out of date, please update to the latest version. Also, make sure you have the tailwindcss configuration file in your project.

<img width="821" alt="coc-tailwindcss3-issue15-1" src="https://user-images.githubusercontent.com/188642/191748430-d94f5685-20b2-443b-b884-1fc13505511f.png">

**Comment by alextes** [comment]
Updated, works now. Little confused, I updated maybe two days ago, but hey, it works!

Thanks for an amazing plugin @yaegassy 💛 !

**Comment by yaegassy** [comment]
See: https://github.com/neoclide/coc.nvim/issues/4212
