### ISSUE TITLE
Highlight Color via vim-css-color

### ISSUE THREAD

**Issue by ShinyJonny** [yaegassy/coc-tailwindcss3#16]
Is there a way to set the filetype of the preview window to css, so that the colors can be highlighted with plugins like `vim-css-color`?

**Comment by ShinyJonny** [comment]
Or maybe it should be a different filetype, as the previews are not valid css, they contain just the css rules.

**Comment by yaegassy** [comment]
> Is there a way to set the filetype of the preview window to css, so that the colors can be highlighted with plugins like `vim-css-color`?

Which window are you referring to by the preview window you are describing? Is it the preview window in the completion menu? It would be helpful if you could post a screenshot.

Perhaps coc-extensions such as coc-tailwindcss3 cannot handle this. Please check if coc.nvim itself can support it. If necessary, please submit a feature request to coc.nvim itself.

**Comment by ShinyJonny** [comment]
> Which window are you referring to by the preview window you are describing? Is it the preview window in the completion menu? It would be helpful if you could post a screenshot.

Yes, I am referring to the completion menu preview.

The menu already supports syntax highlighting, as you can see here:
![Screenshot from 2022-09-25 14-23-24](https://user-images.githubusercontent.com/45402932/192145945-6ac13d32-796c-4811-8607-fd0f41fc44cd.png)

My guess is that its filetype seems to be set to css, but the contents are not valid css, just css rules.
`vim-css-colors` and other highlighters will not highlight invalid css, as you can see here:
![Screenshot from 2022-09-25 14-30-03](https://user-images.githubusercontent.com/45402932/192146098-a0e7e5fe-e6da-4376-9a83-a2a7a356dbdb.png)

When it is a valid css, it will work as expected:
![Screenshot from 2022-09-25 14-30-38](https://user-images.githubusercontent.com/45402932/192146171-d2a40eef-86ef-4509-b64f-e5ace44e9091.png)

It should be possible to resolve the issue by changing the filetype to some other type (the highlighters work for other filetypes too) or reformatting the previews (like wrapping them in an example class definition).

I do not have the exact solution in mind but it looks like something that could be solved and would make the users' lives much easier.

**Comment by ShinyJonny** [comment]
`vim-css-colors` works with just a wrapping of curly brackets:
![image](https://user-images.githubusercontent.com/45402932/192147530-5967a47d-bac1-48d2-9d67-03ed64eba608.png)

But that seems like a hack.

The cleanest implementation would be to parse all the rules that result in a color and highlight them (in the second, i.e. the bottom, preview pane).

**Comment by yaegassy** [comment]
Currently, the language server itself supports highlighting. We will be closing this issue.

- REF: <https://github.com/yaegassy/coc-tailwindcss3/pull/21#issuecomment-1331685610>
