### ISSUE TITLE
Support autocompletion in `tw` tag function from twin.macro

### ISSUE THREAD

**Issue by tupton** [yaegassy/coc-tailwindcss3#18]
This is not so much an issue as a question.

I understand there is a way to add additional attributes that support auto-completion with `tailwindCSS.classAttributes`, but I don't know if it's possible to use that mechanism to autocomplete when using `tw` from [twin.macro](https://github.com/ben-rogerson/twin.macro).

Examples from the `twin.macro` documentation:

```js
import tw from 'twin.macro'

const Input = ({ hasHover }) => (
  <input css={[tw`border`, hasHover && tw`hover:border-black`]} />
)
```

```js
import tw, { css } from 'twin.macro'

const hoverStyles = css`
  &:hover {
    border-color: black;
    ${tw`text-black`}
  }
`
const Input = ({ hasHover }) => (
  <input css={[tw`border`, hasHover && hoverStyles]} />
)
```

**Comment by yaegassy** [comment]
I have never used twin.macro, so I don't know. There may be some issues or discussions on upstream (tailwindcss-intellisense) or twin.macro that may be of interest to you.

- https://github.com/ben-rogerson/twin.macro/discussions/227
- https://github.com/tailwindlabs/tailwindcss-intellisense/issues?q=twin.macro

**Comment by yaegassy** [comment]
Try this setting to `coc-settings.json`. Does it behave the way you expect it to behave?

**coc-setting.json**:

```jsonc
{
  "tailwindCSS.experimental.classRegex": [
      "tw`([^`]*)", // tw`...`
      "tw=\"([^\"]*)", // <div tw="..." />
      "tw={\"([^\"}]*)", // <div tw={"..."} />
      "tw\\.\\w+`([^`]*)", // tw.xxx`...`
      "tw\\(.*?\\)`([^`]*)" // tw(Component)`...`
  ]
}
```

**Comment by tupton** [comment]
Apologies for the _massive_ delay in getting back to you, but yes, those links were very helpful. Thank you for suggesting the config; it works perfectly!
