### ISSUE TITLE
Support twind

### ISSUE THREAD

**Issue by igorbrasileiro** [yaegassy/coc-tailwindcss3#19]
Hi, thank you for this amazing coc extension.
Do you have plans to allow this extension be compatible with the https://twind.dev/ ?!

Another ref: https://github.com/tw-in-js/vscode-twind-intellisense

**Comment by yaegassy** [comment]
I have never used twind and will find time to check it out.

**Comment by igorbrasileiro** [comment]
> I have never used twind and will find time to check it out.

Thank you for the answer.

I'm trying to port, but I don't have enough context and I'm getting an error. Take a look at my changes: https://github.com/igorbrasileiro/coc-tailwindcss3/commit/6db5fa30e5325dbe2db34df86100005b32904b67

I got this error 
![image](https://user-images.githubusercontent.com/15680320/197524878-50c92bf6-2216-41c8-aae3-b7e3a7bd0095.png)

**Comment by yaegassy** [comment]
Try this setting to `coc-settings.json`. Does it behave the way you expect it to behave?

**coc-setting.json**:

```jsonc
{
  "tailwindCSS.experimental.classRegex": [
      "tw`([^`]*)", // tw`...`
      "tw=\"([^\"]*)", // <div tw="..." />
      "tw={\"([^\"}]*)", // <div tw={"..."} />
      "tw\\.\\w+`([^`]*)", // tw.xxx`...`
      "tw\\(.*?\\)`([^`]*)" // tw(Component)`...`
  ]
}
```

**Comment by igorbrasileiro** [comment]
> Try this setting to `coc-settings.json`. Does it behave the way you expect it to behave?
> 
> **coc-setting.json**:
> 
> ```js
> {
>   "tailwindCSS.experimental.classRegex": [
>       "tw`([^`]*)", // tw`...`
>       "tw=\"([^\"]*)", // <div tw="..." />
>       "tw={\"([^\"}]*)", // <div tw={"..."} />
>       "tw\\.\\w+`([^`]*)", // tw.xxx`...`
>       "tw\\(.*?\\)`([^`]*)" // tw(Component)`...`
>   ]
> }
> ```

Hi, i made it work with the tailwind.config.js file into my project folder without this setting, but it doesn't work properlly, since twind has different classes of tailwindcss. For example, twind doesn't have `peer` for siblings, have `siblings`.
About the port, do you know if the coc nvim is capable of run JS file as language server client, because the twind/typescript-plugin doesn't have a executable like tailwind?

**Comment by yaegassy** [comment]
I checked the code for `vscode-twind-intellisense`. This appears to be an extension that needs to work with `tsserver`.

You may find `coc-styled-components` by `fannheyward` helpful.

- <https://github.com/fannheyward/coc-styled-components>

**Comment by igorbrasileiro** [comment]
Ohh, nice, thank you for the help!!
