### ISSUE TITLE
Improve sorting classes

### ISSUE THREAD

**Issue by BrayanCaro** [yaegassy/coc-tailwindcss3#24]
The following class is not sorted incorrectly (the result is `m-2 rounded mt-1.5`),

```html
<div class="m-2 mt-1.5 rounded"></div>
```

Since `mt-1.5` is not explicitly listed on the `package.json`

A quick fix is just to add `mt-1.5`, but I think this plugin could be more awesome if we use another package such as [tailwind-classes-sorter](https://www.npmjs.com/package/tailwind-classes-sorter) (but I couldn't make it work :disappointed:) or we create a new one that accepts a configuration more compact:

```
"tailwindCSS.headwind.defaultSortOrder": {
          "type": "array",
          "default": [
            "m-{value}",
            "mt-{value}",
            ...,
        ]
}
```

**Comment by yaegassy** [comment]
Thanks for the issue report.

Are you using `prettier`? If it is coc.nvim, you can use it by installing `coc-prettier`.

There is an official prettier plugin provided by tailwindcss.

- <https://github.com/tailwindlabs/prettier-plugin-tailwindcss>
- <https://tailwindcss.com/blog/automatic-class-sorting-with-prettier>

If you install this in your project, you will get the sorting you expect when `prettier` is run, so give it a try.
