### ISSUE TITLE
How to use the configuration options

### ISSUE THREAD

**Issue by Mikadifo** [yaegassy/coc-tailwindcss3#25]
I see a lot of configuration options, which I love. I wanted to use `tailwindCSS.emmetCompletions`, but I don't know where to put it or how to use it. I tried using the `:CocConfig` command and including that in the json, but it didn't work. I also tried in my local coc config, and nothing.

**Comment by yaegassy** [comment]
You can configure the settings in `coc-settings.json` as follows.

```jsonc
{
  // ...snip
  "tailwindCSS.emmetCompletions": true,
  // ...snip
}
```

Also, I think you need to install `coc-emmet` to properly utilize the feature of `tailwindCSS.emmetCompletions`.

```
:CocInstall coc-emmet
```

---

**DEMO**:

https://user-images.githubusercontent.com/188642/228697754-b696f72a-def9-4357-95dc-0b745268c286.mp4

**Comment by Mikadifo** [comment]
I installed coc-emmet, but it doesn't shows me the tailwindcss options:

<img width="419" alt="Screenshot 2023-03-29 at 8 52 35 PM" src="https://user-images.githubusercontent.com/51935560/228700158-88eb750f-0291-43eb-a145-fc0088c95c93.png">

**I also tried on html only**
<img width="406" alt="Screenshot 2023-03-29 at 8 53 02 PM" src="https://user-images.githubusercontent.com/51935560/228700217-6d43d49c-866b-4755-8002-e18c41be0cdb.png">

Hope you can help me.

**Comment by yaegassy** [comment]
It's possible that coc-tailwindcss3 is not starting up correctly, or the extension may not work if `workspaceFolders` are empty. <https://github.com/yaegassy/coc-tailwindcss3#workspacefolders>

Please try again with a minimal project directory configuration.

```
mkdir -p /tmp/twcheck
cd /tmp/twcheck
git init
npm init -y
npm i tailwindcss
npx tailwindcss init
```

In this case, the directory that contains `.git` will be the `workspaceFolders`.

**Comment by Mikadifo** [comment]
Didn't work. It only doesn't work when using emmet, the extension works fine in normal class= or className=.

**Comment by yaegassy** [comment]
Does "className=" refer to jsx/tsx? Indeed, it seems that it does not work with jsx/tsx. I do not know the reason for this.

**Comment by yaegassy** [comment]
I tried `vue` files in my environment and they seemed to work. I'm not sure why they don't work with `jsx/tsx` though...

<img width="458" alt="coc-tailwindcss3-issue-25-2" src="https://user-images.githubusercontent.com/188642/228708864-c9273feb-1a16-4f7b-8e79-0dbfa4773643.png">

**Comment by yaegassy** [comment]
Regarding the issue where the functionality of the `tailwindCSS.emmetCompletions` setting was not working in `jsx/tsx`, we were able to address it by making adjustments to `coc-tailwindcss3`, so we have adjusted the functionality.

<img width="475" alt="coc-tailwindcss3-issue-25-3" src="https://user-images.githubusercontent.com/188642/228736347-f9b0590e-c7b6-46be-aeb9-090d2ef7309a.png">

**Comment by Mikadifo** [comment]
`tailwindCSS.emmetCompletions` configuration works now on jsx files, thank you!
