### ISSUE TITLE
Highlighted colours?

### ISSUE THREAD

**Issue by chaudry-786** [yaegassy/coc-tailwindcss3#27]
Is it possible to show colours like vscode?
![Screenshot from 2023-03-31 11-09-39](https://user-images.githubusercontent.com/73726199/229092046-5d13ca8f-902c-4112-851d-3ab27864713c.png)

**Comment by yaegassy** [comment]
I don't know what part of the color you are assuming, but please refer to the following issue comments.

- <https://github.com/yaegassy/coc-tailwindcss3/pull/21#issuecomment-1331685610>

**Comment by chaudry-786** [comment]
ahh great, any chance it could be just like VsCode. box highlighted in appropriate colour? rather than whole text?

Also is it possible to show the colours in dropdown?

**Comment by yaegassy** [comment]
coc-tailwindcss3 itself does not have that functionality. Please look for a plugin that behaves the way you expect and install it additionally.
