### ISSUE TITLE
Is it possible to support attributify like unocss?

### ISSUE THREAD

**Issue by wanaiqing** [yaegassy/coc-tailwindcss3#31]
As described in title..

**Comment by yaegassy** [comment]
I found a coc-extension called coc-unocss from the [coc.nvim wiki](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions).

- <https://github.com/auvred/coc-unocss>

I haven't tried it because I don't use unocss, but you might want to try this extension.

**Comment by wanaiqing** [comment]
> I found a coc-extension called coc-unocss from the [coc.nvim wiki](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions).
> 
> * https://github.com/auvred/coc-unocss
> 
> I haven't tried it because I don't use unocss, but you might want to try this extension.

Thank you, I've just tried,  it's useful although a little buggy...
