### ISSUE TITLE
it's not work that in monorepo

### ISSUE THREAD

**Issue by vegawong** [yaegassy/coc-tailwindcss3#4]

**Comment by vegawong** [comment]
Such as this folder.
```
├─ root
 │   ├─ packages
 │    │    ├─ pkg1
 │    │     │    ├─ src
 │    │     │     │    ├─ index.html
 │    │     │    ├─ tailwind.config.js
 │    │    ├─ pkg2
 │    │     │    ├─ src
 │    │     │     │    ├─ index.html
 │    │     │    ├─ tailwind.config.js

```
open vim with the root path, and edit `packages/pkg1/src/index.html` or `packages/pkg2/src/index.html`, the coc extension is not actived.

**Comment by yaegassy** [comment]
It is assumed that if a configuration file for tailwindcss such as `tailwind.config.js` or `tailwind.config.cjs` exists in the project, the extension will be activated, but apparently it is not working properly.

Changed the conditions under which extensions are enabled. Please upgrade `@yaegassy/coc-tailwindcss3`.

**Comment by yaegassy** [comment]
@vegawong I have found that there is a problem with what I have adjusted in this issue. Sorry, but we will revert...

---

For monorepo and others, add this setting to .vimrc or init.vim.

**e.g. html filetype**:

```
  au FileType html let b:coc_root_patterns = ['.git', '.env', 'tailwind.config.js', 'tailwind.config.cjs']
```

Then `cd` (cli) to the folder where `tailwind.config.{js,cjs}` resides and start Vim/Neovim.

**Comment by yaegassy** [comment]
Even projects like monorepo have added a command to force activation of this extension. Please update `@yaegassy/coc-tailwindcss3`.

```vim
:CocCommand tailwindCSS.forceActivate
```
