### ISSUE TITLE
Headwind integration

### ISSUE THREAD

**Issue by zachschultz** [yaegassy/coc-tailwindcss3#5]
First off, thank you for creating this extension! I'd like to know if there are any plans to re-integrate Headwind with this, and if not, if you have any pointers on how one could integrate it themselves.

**Comment by yaegassy** [comment]
Are you using `prettier`? With coc.nvim, you can use `coc-prettier`. You can use the official (tailwindlabs) `prettier-plugin-tailwindcss`. <https://github.com/tailwindlabs/prettier-plugin-tailwindcss>

If you install `prettier-plugin-tailwindcss` in your project, the sorting will work.

**Comment by zerodogg** [comment]
While I'd love to use prettier, that's sometimes not an option. There's no working plugin for nunjucks, for instance. Having this in the coc plugin would solve that usecase (though I understand it might be out of the intended scope).

**Comment by yaegassy** [comment]
OK, I will try to add `headwind` feature assuming it is used with file types not supported by `prettier`.

**Comment by yaegassy** [comment]
Done.

**Comment by zerodogg** [comment]
Wow, you're fast. Thank you very much!
