### ISSUE TITLE
It doesn't recognize SvelteKit project

### ISSUE THREAD

**Issue by pepperoni21** [yaegassy/coc-tailwindcss3#9]
Hi, the extension is not working on my SvelteKit project.

TailwindCSS is properly installed and the IntelliSense works perfectly on VSCode.

Here's my project's structure:
![Screenshot_145](https://user-images.githubusercontent.com/29759371/179554567-afb70b23-79cc-4d32-b467-fa766be24fd1.png)

Here's everything I've tried so far:
- Opening nvim in the root folder and in the src folder
- Using tailwindCSS.forceActivate
- Opening my tailwind.config.cjs file
- Renaming it to tailwind.config.js
- Reinstalling the extension and the COC plugin
- Creating an index.html file to see if it works with basic html files

Nothing works, so I really don't know what to do, thanks for reading.

**Comment by yaegassy** [comment]
It works fine with sveltekit in my environment. I followed the instructions on this page for installing tailwindcss in sveltekit. <https://tailwindcss.com/docs/guides/sveltekit>

<img width="755" alt="coc-tailwindcss3-sveltekit-check" src="https://user-images.githubusercontent.com/188642/179582414-9214b227-c6db-4be5-b356-f69ddd059b8e.png">

---

Try running `:CocCommand tailwindCSS.showOutput`. You may be able to find out some information that may be causing the problem.

Or try `:echo WorkspaceFolders`. Make sure it is the same as the project root directory you expect.

**Comment by pepperoni21** [comment]
Thank you for your answer. I tried running `:CocCommand tailwindCSS.showOutput` but it opens me an empty buffer, and `:echo WorkspaceFolders` returns me my root directory.

I also tried testing the extension on a basic html project with tailwindcss and a Next.JS project, it didn't work for both, so the problem is not related to SvelteKit. Is there any dependency I need besides coc.nvim, coc-html and coc-css ?

**Comment by yaegassy** [comment]
> I also tried testing the extension on a basic html project with tailwindcss and a Next.JS project, it didn't work for both, so the problem is not related to SvelteKit. Is there any dependency I need besides coc.nvim, coc-html and coc-css ?

No dependence on other coc extensions. If you put `.git` in the directory where `tailwind.config.js` or `tailwind.config.cjs` exists, will it not work?

I am unable to reproduce the non-working situation in my environment. If you give me a reproducible case, I will try.

**Comment by yaegassy** [comment]
Otherwise, the only other thing I can think of is to update `coc.nvim` to the latest version and try
